#include <iostream>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <ctime>
#include <algorithm>
#include <string>
#include <cstring>
#include <chrono>
#include <twojastara>
#include <vector>
#include <iomanip>
#include <queue>
#include <list>
#include <stack>
#include <bitset>
#include <regex>
#include <thread>